compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: path/StableAvatar/deepspeed_config/zero_stage2_config.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: False
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
main_training_function: main
dynamo_backend: 'no'
num_machines: 8
num_processes: 64
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false